"""Features quantitativas (OHLCV -> features)."""

from quantmaster.features.microstructure import (
    amihud_illiquidity,
    corwin_schultz_spread,
    relative_spread_proxy,
    roll_spread,
)
from quantmaster.features.momentum import chande_momentum_oscillator, rsi, time_series_momentum
from quantmaster.features.regime import (
    cusum_statistic,
    market_efficiency_index,
    runs_test_statistic,
    variance_ratio,
)
from quantmaster.features.risk import (
    expected_shortfall,
    max_drawdown_duration,
    tail_risk_measure,
    value_at_risk_historical,
)
from quantmaster.features.returns import intraday_return, overnight_gap
from quantmaster.features.statistical import (
    approximate_entropy,
    cross_sample_entropy,
    downside_beta,
    fracdiff,
    hurst_dfa,
    information_discreteness,
    ornstein_uhlenbeck,
    permutation_entropy,
    realized_kurtosis,
    realized_skewness,
    rolling_beta,
    sample_entropy,
)
from quantmaster.features.trend import (
    kaufman_efficiency_ratio,
    price_acceleration,
    trend_intensity,
    trend_strength_autocorr,
    trend_strength_indicator,
)
from quantmaster.features.volume import rvol
from quantmaster.features.volatility import (
    bipower_variation,
    harq_adjustment,
    garman_klass_volatility,
    har_rv,
    har_rv_forecast,
    intraday_range,
    jump_variation,
    log_volatility_increment,
    medrv,
    minrv,
    parkinson_volatility,
    realized_quarticity,
    realized_roughness,
    realized_semivariance,
    realized_variance,
    rogers_satchell_volatility,
    shar_components,
    signed_jump_variation,
    volatility_ratio,
    yang_zhang_volatility,
)

__all__ = [
    "amihud_illiquidity",
    "approximate_entropy",
    "bipower_variation",
    "corwin_schultz_spread",
    "cross_sample_entropy",
    "cusum_statistic",
    "downside_beta",
    "expected_shortfall",
    "fracdiff",
    "garman_klass_volatility",
    "harq_adjustment",
    "har_rv",
    "har_rv_forecast",
    "hurst_dfa",
    "intraday_return",
    "intraday_range",
    "information_discreteness",
    "jump_variation",
    "log_volatility_increment",
    "market_efficiency_index",
    "max_drawdown_duration",
    "medrv",
    "minrv",
    "ornstein_uhlenbeck",
    "overnight_gap",
    "permutation_entropy",
    "parkinson_volatility",
    "realized_quarticity",
    "realized_kurtosis",
    "realized_roughness",
    "realized_semivariance",
    "realized_skewness",
    "realized_variance",
    "relative_spread_proxy",
    "rogers_satchell_volatility",
    "shar_components",
    "signed_jump_variation",
    "roll_spread",
    "runs_test_statistic",
    "rvol",
    "rsi",
    "chande_momentum_oscillator",
    "rolling_beta",
    "tail_risk_measure",
    "time_series_momentum",
    "sample_entropy",
    "value_at_risk_historical",
    "variance_ratio",
    "volatility_ratio",
    "trend_intensity",
    "kaufman_efficiency_ratio",
    "price_acceleration",
    "trend_strength_indicator",
    "trend_strength_autocorr",
    "yang_zhang_volatility",
]
